package com.example.flood.situation.domain;

public enum MetricCode {
    RAINFALL_24H_MM, WATER_LEVEL_OVER_WARNING_M, MAX_WATER_DEPTH_M, AFFECTED_AREA_KM2,
    AFFECTED_POPULATION, TRAPPED_POPULATION, EVACUATED_POPULATION, VULNERABLE_POPULATION,
    INJURED_POPULATION, MISSING_POPULATION, DEATH_POPULATION, DAMAGED_HOUSEHOLDS,
    COLLAPSED_HOUSES, ROAD_INTERRUPTIONS, CRITICAL_FACILITIES_AFFECTED,
    POWER_OUTAGE_HOUSEHOLDS
}
